Add files via upload

diff --git a/frlm b/frlm
--- a/frlm
+++ b/frlm
@@ -6,16 +6,24 @@
 yellow='\e[1;33m'
 green='\e[0;34m'
 BlueF='\e[1;34m'
+Red="\e[1;31m"
+Cclear="\e[0m"
 path=$(pwd)
 clear
-# check for root access
-if [[ $UID -ne 0 ]]
-then
-	echo 'sudo !!'
-	echo
+
+fi
+################################# < Super User Check > ################################
+if [ $EUID -ne 0 ]; then
+	echo -e "${Red}You don't have admin privilegies, execute the script as root.$Cclear"
 	exit 1
 fi
 
+################################### < XTerm Checks > ###################################
+if [ ! "${DISPLAY:-}" ]; then
+    echo -e "${CRed}The script should be exected inside a X (graphical) session.$CClr"
+    exit 2
+fi
+########################################################################################
 arg=$1
 mode=$2
 interface=$3
@@ -70,6 +78,15 @@ elif
 elif
 [ " $arg " = ' open ' ] ; then
 	nautilus --browser $path
+elif
+[ " $arg " = ' fix ' ] ; then
+	 rm /var/lib/dpkg/lock
+	 dpkg --configure -a
+	 rm /var/lib/apt/lists/lock
+	 rm /var/cache/apt/archives/lock
+ elif
+ [ " $arg " = ' update ' ] ; then
+ apt-get -y update && apt-get -y upgrade && apt-get -y dist-upgrade
 elif [ " $arg " = ' -h ' ] || [ " $arg " = ' --help ' ]; then
 		echo ""
 		echo "[option]"
@@ -87,6 +104,10 @@ elif [ " $arg " = ' -h ' ] || [ " $arg " = ' --help ' ]; then
 		echo " chess = start lichess in localhost "
 		echo ""
 		echo " open "
+		echo ""
+		echo " fix = Fix “Unable to lock the administration directory (/var/lib/dpkg/)“ "
+		echo ""
+		echo " update = update the system "
 		echo ""
 		echo " -h = help "
 		echo ""
